# Generated by Django 3.0.4 on 2020-03-11 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField(auto_now=True)),
                ('agenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='medicar.Agenda')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
