# Generated by Django 3.0.4 on 2020-03-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='data',
            new_name='dia',
        ),
    ]
