# Generated by Django 3.0.4 on 2020-03-10 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicar', '0002_auto_20200310_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='disponibilidade',
            new_name='horario',
        ),
        migrations.RenameField(
            model_name='horario',
            old_name='horarios',
            new_name='horario',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='CRM',
            new_name='crm',
        ),
    ]
